# Pipeline for Develop PR

name: $(Date:yyyyMMdd)$(Rev:r)

trigger: none
pr:
- develop

pool:
  vmImage: $(VMImage)

steps:
- template: Base-Steps.yml
  parameters:
    NugetVersion : '$(MAJOR).$(MINOR).$(PATCH)-alpha'
