# Pipeline for Develop CI

name: $(Date:yyyyMMdd)$(Rev:r)

trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - README.md
pr: none

pool:
  vmImage: $(VMImage)

steps:
- template: Base-Steps.yml
  parameters:
    NugetVersion : '$(MAJOR).$(MINOR).$(PATCH)-$(PRE_RELEASE)'
    Publish: 'true'