# Pipeline for Master CI

name: $(Date:yyyyMMdd)$(Rev:r)

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
pr: none

pool:
  vmImage: $(VMImage)

steps:
- template: Base-Steps.yml
  parameters:
    NugetVersion : '1.0.1' #'$(MAJOR).$(MINOR).$(PATCH)'
    Publish: 'true'